version: "3"
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - "./dist/postgresql/data/:/var/lib/postgresql/data"
    depends_on:
      - backend
  backend:
    image: junboss/sef:0.1.1
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports :
      - "8080:8080"
    volumes:
      - './backend:/app'
      - '/app/node_modules'
#    env_file:
#      - .env.development
#      - .env.production
