# dev 이동 예정
version: "3"
services:
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - "./dist/postgresql/data/:/var/lib/postgresql/data"
  backend:
      image: junboss/sef:0.1.1
      build:
        context: ./backend
        dockerfile: backend/Dockerfile.dev
      ports :
        - "8080:8080"
      volumes:
        - './backend:/app'
        - '/app/node_modules'
  #    env_file:
  #      - .env.production
