version: "3"
services:
  nginx:
    image: nginx:stable
    ports:
      - "4000:5000"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    container_name: sef-proxy
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - db
      - backend
  db:
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    networks:
      - app-network
    environment:
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    volumes:
      - "./dist/postgresql/data/:/var/lib/postgresql/data"
  backend:
    image: junboss/sef:0.1.1
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - './backend:/app'
      - '/app/node_modules'
    networks:
      - app-network
    depends_on:
      - db
    container_name: sef-backend

networks:
  app-network:
    driver: bridge